---
# See 'https://goreleaser.com'.

# yaml-language-server: $schema=https://goreleaser.com/static/schema.json

version: 2

before:
  hooks:
    - go mod tidy

gomod:
  proxy: true

builds:
  - env:
      - CGO_ENABLED=0
      - GAMON3_VERSION={{ if index .Env "GAMON3_VERSION" }}{{ .Env.GAMON3_VERSION }}{{ else }}{{ .Version }}{{ end }}
    goos:
      - darwin
      - linux
    flags:
      - -v
      - -buildvcs=auto
      - -trimpath
    ldflags:
      - -s -w
      - -X main.Version={{.Env.GAMON3_VERSION}}

archives:
  - formats: [tar.gz]
    name_template: >-
      {{ .ProjectName }}_
      {{- .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    wrap_in_directory: true
    format_overrides:
      - goos: darwin
        formats: [tar.gz, zip]

release:
  footer: >-

    ---

    Released by [semantic-release](https://github.com/semantic-release/semantic-release) and [GoReleaser](https://github.com/goreleaser/goreleaser).
