---
preset: conventionalcommits

plugins:
  - - "@semantic-release/commit-analyzer"
    # See 'https://github.com/semantic-release/commit-analyzer#releaserules'.
    - releaseRules:
        - type: perf
          release: minor

        - type: docs
          scope: README
          release: patch

        - type: refactor
          release: patch

        - type: style
          release: patch

  - - "@semantic-release/release-notes-generator"
    # See 'https://github.com/semantic-release/release-notes-generator#options'.
    # See 'https://github.com/conventional-changelog/conventional-changelog/tree/master/packages/conventional-changelog-conventionalcommits#specific-options'.
    # See 'https://github.com/conventional-changelog/conventional-changelog-config-spec/blob/master/versions/2.2.0/README.md#types'.
    - presetConfig:
        types:
          - type: feat
            section: Features
          - type: perf
            section: Features

          - type: fix
            section: Bug Fixes

          - type: docs
            scope: README
            section: Documentation

          - type: style
            section: Other
          - type: refactor
            section: Other

          - type: chore
            hidden: true
          - type: test
            hidden: true

  - - "@semantic-release/changelog"
    - changelogFile: "CHANGELOG.md"

  - - "@semantic-release/git"
    - assets:
        - CHANGELOG.md
      message: "chore(release): ${nextRelease.version} [skip ci]"

  - - "@semantic-release/exec"
    - publishCmd: |
        echo "${nextRelease.notes}" > /tmp/release-notes.md
        goreleaser release --release-notes /tmp/release-notes.md --clean
