#!/usr/bin/env sh

# Rename Go Module.

# REMEMBER TO UPDATE CUR AND NEW WHEN USING THIS SCRIPT.
export CUR="github.com/peter-bread/gamon3"
export NEW="github.com/peter-bread/gamon3/v2"

go mod edit -module "$NEW"
find . -type f -name '*.go' -exec perl -pi -e 's/$ENV{CUR}/$ENV{NEW}/g' {} \;
