---
name: release

on:
  workflow_dispatch:

jobs:
  release:

    permissions:
      contents: write
      issues: write
      pull-requests: write

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - uses: actions/setup-go@v6
        with:
          go-version: '1.25'

      - name: Install GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          version: "~> v2"
          install-only: true

      - name: Show GoReleaser version
        run: goreleaser -v

      - uses: actions/setup-node@v5
        with:
          node-version: 20

      - run: npm ci

      - run: npm run release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
