---
name: release

on:
  workflow_dispatch:

jobs:
  release:

    permissions:
      contents: write
      issues: write
      pull-requests: write

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - uses: actions/setup-go@v6
        with:
          go-version: '1.25'

      - name: Install GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          version: "~> v2"
          install-only: true

      - name: Show GoReleaser version
        run: goreleaser -v

      - uses: actions/setup-node@v5
        with:
          node-version: 20

      - run: npm ci

      - run: npm run release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  bump-homebrew-formula:
    runs-on: ubuntu-latest

    needs: release
    if: ${{ needs.release.result == 'success' }}

    env:
      OWNER: ${{ github.repository_owner }}
      REPO: ${{ github.event.repository.name }}
      TAP: ${{ vars.HOMEBREW_TAP }}

    steps:

      - uses: actions/create-github-app-token@v2
        id: app-token
        with:
          app-id: ${{ vars.CELLARMAN_APP_ID }}
          private-key: ${{ secrets.CELLARMAN_APP_PRIVATE_KEY }}
          owner: ${{ env.OWNER }}
          repositories: ${{ env.TAP }}

      - uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ steps.app-token.outputs.token }}
          repository: ${{ env.OWNER }}/${{ env.TAP }}
          event-type: bump
          client-payload: |-
            {
              "formula": "${{ env.REPO }}"
            }
