---
name: test

on:
  workflow_dispatch:

jobs:
  dispatch:
    runs-on: ubuntu-latest

    env:
      SOFTWARE_OWNER: peter-bread
      SOFTWARE_REPO: gamon3
      TAP_OWNER: peter-bread
      TAP_REPO: homebrew-tap

    steps:

      - uses: actions/create-github-app-token@v2
        id: app-token
        with:
          app-id: ${{ vars.HOMEBREW_DISPATCH_APP_ID }}
          private-key: ${{ secrets.HOMEBREW_DISPATCH_APP_KEY }}
          owner: ${{ github.repository_owner }}
          repositories: ${{ env.TAP_REPO }}

      - name: Get latest release info
        id: release-info
        run: |
          LATEST=$(curl -s "https://api.github.com/repos/$SOFTWARE_OWNER/$SOFTWARE_REPO/releases/latest")
          TAG=$(echo "$LATEST" | jq -r '.tag_name')
          URL=$(echo "$LATEST" | jq -r '.tarball_url')

          wget -O /tmp/gamon.tar.gz "$URL"
          CHECKSUM=$(sha256sum /tmp/gamon.tar.gz | cut -d ' ' -f1)

          echo "tag=$TAG" >> "$GITHUB_OUTPUT"
          echo "checksum=$CHECKSUM" >> "$GITHUB_OUTPUT"

      - uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ steps.app-token.outputs.token }}
          repository: ${{ env.TAP_OWNER }}/${{ env.TAP_REPO }}
          event-type: my-event
          client-payload: |-
            {
              "release": {
                "tag": "${{ steps.release-info.outputs.tag }}",
                "checksum": "${{ steps.release-info.outputs.checksum }}"
              }
            }
