---
name: test

on:
  workflow_dispatch:

jobs:
  dispatch:
    runs-on: ubuntu-latest

    env:
      OWNER: peter-bread
      REPO: homebrew-tap

    steps:

      - uses: actions/create-github-app-token@v2
        id: app-token
        with:
          app-id: ${{ vars.HOMEBREW_DISPATCH_APP_ID }}
          private-key: ${{ secrets.HOMEBREW_DISPATCH_APP_KEY }}
          owner: ${{ github.repository_owner }}
          repositories: |
            ${{ env.REPO }}

      - uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ steps.app-token.outputs.token }}
          repository: ${{ env.OWNER }}/${{ env.REPO }}
          event-type: my-event
